export default {
    PRIMARY_COLOR: '#4a148c',
    ACCENT_COLOR: 'ff6f00',
    DEFAULT_WHITE: '#FFFFFF',
    DEFAULT_BLACK:'#1E2128',
    DEFAULT_DARK_GRAY: '#91908D',
    DEFAULT_LIGHT_GRAY: '#E0DED9',
    MEALITEM_BG_COLOR: '#f5f5f5'
}